# Generated by Django 3.1.2 on 2021-03-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('password', models.TextField()),
                ('userType', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'bankuser',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('transactionType', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('bankUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bankusers')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
